adobe/aem-sidekick

custom-elements.json
rollup.config.js
src/extension/app/aem-sidekick.js
src/extension/content.js
src/extension/index.js

1. Export AemSidekick class from `index.js`
2. Instantiate AemSidekick instance in content script, passing in the config object in the constructor
3. Fix open toggle
4. Make AemSidekick fullscreen (but not blocking interaction with the page behind it).

fix: initialize sidekick with config

---

src/extension/project.js
src/extension/url-cache.js
test/wtr/project.test.js

feat: transient match from url cache

---

src/extension/content.js

fix: re-entry check

---

src/extension/app/aem-sidekick.js
src/extension/app/store/site.js
src/extension/auth.js
src/extension/background.js
src/extension/content.js
src/extension/display.js
src/extension/log.js
src/extension/project.js
src/extension/tab.js
src/extension/url-cache.js
test/wtr/auth.test.js
test/wtr/log.test.js
test/wtr/project.test.js
test/wtr/tab.test.js

feat: logging

---

src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/action-bar/menu-item/menu-item.js
src/extension/app/components/plugin/palette-container.js
src/extension/app/components/plugin/palette-dialog/palette-dialog-wrapper.js
src/extension/app/utils/browser.js
test/wtr/app/components/plugin/palette-container.test.js
test/wtr/app/components/plugin/plugin-action-bar.test.js
test/wtr/app/utils/browser.test.js
test/wtr/app/utils/event-bus.test.js
test/wtr/app/utils/i18n.test.js
test/wtr/fixtures/stubs/helix-admin.js

More coverage of palette container
Ignore overridden spectrum web components from coverage (typically only overridden for styling or minimal code changes)
100% coverage of utils

Palette container utils coverage

---

src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/action-bar/picker/picker.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.js

- Fix env switcher menu-item text color in light mode
- Disable env switcher until status call has completed
- Fix disabled state background colors when button is blue and green.

fix: env switcher styling

---

src/extension/app/components/modal/modal-container.js
src/extension/app/components/plugin/env-switcher/env-switcher.js
src/extension/app/plugins/preview/preview.js
src/extension/app/plugins/publish/publish.js
src/extension/app/store/app.js
src/extension/app/store/site.js

Add and use i18n helper function on appStore

fix: add and use i18n helper function on appStore

---

src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/plugins/env/env.js
test/wtr/app/components/plugin/plugin-action-bar.test.js
test/wtr/fixtures/helix-admin.js
test/wtr/mocks/environment.js

feat: tweak env switcher

---

src/extension/app/aem-sidekick.css.js
src/extension/app/components/action-bar/picker/picker.css.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/spectrum-2.css.js
src/extension/views/json/json.css.js

* Set `min-width` of sidekick to 620px.. `max-width` to 800px
* Fix disabled button color in env-switcher
* Set sidekick border radius to 12px

fix: ui tweaks

---

src/extension/actions.js
src/extension/auth.js
src/extension/project.js
test/auth.test.js

feat: reuse auth token within the same org

---

src/extension/app/components/plugin/palette-container.js
src/extension/app/components/plugin/palette-dialog/palette-dialog-wrapper.js

fix: palette styling

---

src/extension/app/store/app.js
test/app/components/plugin/plugin-action-bar.test.js
test/fixtures/helix-admin.js

feat: load local resources in dev mode

---

src/extension/app/aem-sidekick.css.js
src/extension/app/plugins/preview/preview.js
src/extension/app/store/app.js
src/extension/app/utils/rum.js
src/extension/content.js
src/extension/rum.js
test/app/plugins/preview/preview.test.js
test/app/store/app.test.js

Avoid confusing side effects between the current and new sidekick.

chore: separate namespace for new sidekick

---

rollup.config.js
src/extension/manifest.json

json view was getting bundled after the zip was created....

fix: change build order

---

src/extension/project.js
test/project.test.js
test/ui.test.js

feat: add project should fetch from config.json

---

src/extension/app/store/app.js
test/app/store/app.test.js

fix: validate session

---

src/extension/app/plugins/delete/delete.js
src/extension/app/plugins/unpublish/unpublish.js
test/app/plugins/delete/delete.test.js
test/app/plugins/unpublish/unpublish.test.js

fix: delete/unpublish claim source document is missing

---

src/extension/background.js
src/extension/project.js
src/extension/tab.js
src/extension/utils/admin.js
test/project.test.js
test/tab.test.js

fix: sidekick no longer opening in dev

---

src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/store/app.js
src/extension/app/store/site.js
src/extension/types/typedefs.js
test/app/components/plugin/env-switcher.test.js
test/app/store/app.test.js
test/fixtures/helix-admin.js
test/fixtures/sidekick-config.js

chore: switch to contentSourceUrl and contentSourceType

---

src/extension/_locales/en/messages.json
src/extension/app/components/bulk/bulk-result/bulk-result.js
src/extension/app/components/modal/modal-container.js
src/extension/app/components/plugin/env-switcher/env-switcher.js
src/extension/app/plugins/bulk/bulk-copy-urls.js
src/extension/app/plugins/bulk/bulk-preview.js
src/extension/app/plugins/bulk/bulk-publish.js
src/extension/app/plugins/preview/preview.js
src/extension/app/plugins/reload/reload.js
src/extension/app/store/app.js
src/extension/app/store/bulk.js
src/extension/app/utils/admin-client.js
test/app/store/app.test.js
test/app/store/bulk.test.js
test/app/utils/admin-client.test.js

feat: special handling for config files

---

src/extension/project.js
src/extension/url-cache.js
test/fixtures/discover.js
test/mocks/discover.js
test/project.test.js
test/url-cache.test.js

feat: ignore originalSite if single match

---

src/extension/app/store/bulk.js
src/extension/app/utils/admin-client.js
test/app/utils/admin-client.test.js

chore: make unsuccessful toasts stickier

---

src/extension/actions.js

fix: remove project on prod host not working

---

src/extension/actions.js
src/extension/app/aem-sidekick.css.js
src/extension/app/components/action-bar/picker/picker.js
src/extension/app/components/spectrum/action-menu/action-menu.js
src/extension/auth.js
src/extension/background.js
src/extension/project.js
test/auth.test.js

feat: support cross origin request to tools and labs

---

.husky/pre-commit
src/extension/app/aem-sidekick.js
src/extension/app/constants.js
src/extension/app/store/app.js
test/aem-sidekick.test.js
test/app/store/app.test.js

fix: dispatch sidekick-ready, test statusfetched

---

src/extension/app/components/plugin/plugin-action-bar.js
test/app/components/plugin/plugin-action-bar.test.js

fixes: #255 
Can test with
https://adobe.sharepoint.com/:w:/r/sites/AdobeStateandLocal/_layouts/15/Doc.aspx?sourcedoc=%7B5F20999E-F3E9-420D-AB2C-35144B018DBF%7D&file=index.docx&action=default&mobileredirect=true
^^ Original document with that the issue was noticed on

fix: update right side width calculation

---

src/extension/app/plugins/publish/publish.js
src/extension/app/plugins/reload/reload.js
src/extension/app/store/app.js
test/app/plugins/publish/publish.test.js
test/app/plugins/reload/reload.test.js

fix: obsolete success toasts

---

custom-elements.json
src/extension/actions.js
src/extension/app/store/app.js
src/extension/app/utils/browser.js
src/extension/auth.js
test/app/components/plugin/login.test.js
test/app/store/app.test.js
test/auth.test.js

feat: support transient site token

---

src/extension/app/store/app.js
src/extension/app/store/site.js
src/extension/types/typedefs.js
test/app/store/app.test.js
test/app/store/site.test.js

Fix #244 
(complete PR checks for #245 from @auniverseaway before merging to `main`)

GH-244 - Extensible source support (#245)

---

custom-elements.json
package-lock.json
package.json
src/extension/_locales/en/messages.json
src/extension/actions.js
src/extension/app/components/dialog-wrapper/dialog-wrapper.js
src/extension/app/plugins/publish/publish.js
src/extension/app/store/app.js
src/extension/app/store/site.js
src/extension/app/utils/browser.js
src/extension/auth.js
src/extension/display.js
src/extension/types/typedefs.js
src/extension/ui.js
src/extension/utils/rum.js
test/app/components/plugin/login.test.js
test/app/plugins/publish/publish.test.js
test/app/store/app.test.js
test/app/store/site.test.js
test/auth.test.js
test/display.test.js

Fix #244 
Fix #260 
Fix #261
Fix #265

chore(release): 2024-09-24

---

src/extension/app/store/bulk.js
test/app/components/bulk/bulk-info.test.js
test/fixtures/content-sources.js
test/sidekick-test.js

Fix for localized Sharepoint file selection (non-latin)

---

src/extension/views/json/json.js

fix: JSON view should not attempt to draw links for glob paths

---

src/extension/app/components/action-bar/action-bar.js
src/extension/app/components/action-bar/activity-action/activity-action.css.js
src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/bulk/bulk-info/bulk-info.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.css.js
src/extension/app/components/plugin/login/login.js
src/extension/app/components/theme/theme.js
src/extension/app/spectrum-2.css.js
src/extension/index.js
src/extension/views/json/json.css.js
src/extension/views/json/json.js

Use spectrum 2 SWC theme as the base

fix: use spectrum 2 SWC theme

---

src/extension/app/components/action-bar/activity-action/activity-action.js
src/extension/app/components/modal/modal-container.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/plugins/delete/delete.js
src/extension/app/plugins/preview/preview.js
src/extension/app/plugins/publish/publish.js
src/extension/app/plugins/reload/reload.js
src/extension/app/plugins/unpublish/unpublish.js
src/extension/app/store/app.js
src/extension/app/store/bulk.js
src/extension/app/utils/admin-client.js
src/extension/types/typedefs.js
test/app/components/action-bar/activity-action.test.js
test/app/plugins/delete/delete.test.js
test/app/plugins/preview/preview.test.js
test/app/plugins/publish/publish.test.js
test/app/plugins/reload/reload.test.js
test/app/plugins/unpublish/unpublish.test.js
test/app/store/app.test.js
test/app/store/bulk.test.js
test/app/utils/admin-client.test.js

refactor: toast handling

---

src/extension/views/json/json.js

Glob paths json fix

---

src/extension/actions.js
src/extension/auth.js
test/actions.test.js

feat: api to get auth info

---

package-lock.json
src/extension/_locales/en/messages.json
src/extension/app/utils/admin-client.js
test/actions.test.js
test/app/utils/admin-client.test.js

fix: handle status 400

---

src/extension/_locales/en/messages.json
src/extension/app/plugins/reload/reload.js
test/app/plugins/reload/reload.test.js

feat: rename reload button to update

---

src/extension/_locales/en/messages.json
src/extension/actions.js
src/extension/app/aem-sidekick.js
src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/bulk/bulk-info/bulk-info.css.js
src/extension/app/components/dialog-wrapper/dialog-wrapper.css.js
src/extension/app/components/modal/modal-container.js
src/extension/app/components/plugin/env-switcher/env-switcher.js
src/extension/app/components/plugin/plugin-action-bar.css.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/constants.js
src/extension/app/plugins/reload/reload.js
src/extension/background.js
src/extension/manifest.json
src/extension/project.js
test/actions.test.js
test/aem-sidekick.test.js
test/app/components/modal/modal.test.js
test/app/components/plugin/plugin-action-bar.test.js
test/app/plugins/reload/reload.test.js
test/app/store/app.test.js
test/fixtures/helix-admin.js
test/project.test.js

Release collection PR:
Fix #283
Fix #297
Fix #303

feat: release 2024-10-07

---

package-lock.json
package.json
src/extension/manifest.json
src/extension/tab.js

Adjust homepage and remove share URL from `host_permissions`.

chore: update host permissions and homepage

---

CHANGELOG.md
package.json
src/extension/_locales/en/messages.json
src/extension/app/plugins/edit/edit.js
src/extension/app/store/app.js
src/extension/manifest.json
test/app/components/plugin/plugin-action-bar.test.js
test/app/plugins/edit/edit.test.js

feat: edit plugin

---

src/extension/app/config-picker.css.js
src/extension/project.js
test/actions.test.js
test/fixtures/discover.js
test/mocks/discover.js
test/project.test.js
test/url-cache.test.js

feat: match multiple original sites in url cache

---

src/extension/_locales/en/messages.json
src/extension/app/components/action-bar/picker/picker.js
test/app/components/plugin/palette-container.test.js
test/app/store/app.test.js

fix: disable manageSelection in env picker

---

src/extension/views/json/json.js

[Issue](https://github.com/adobe/helix-sidekick-extension/issues/842)

fix: no cache json fetch

---

src/extension/content.js

fix: multiple config picker elements in dom

---

src/extension/app/components/onboarding/onboarding-dialog.js
src/extension/app/components/plugin/plugin-action-bar.js

- Fix overflow logic
- Fix onboarding sort order

fix: overflow logic and onboarding sort order

---

src/extension/app/aem-sidekick.css.js
src/extension/app/components/onboarding/onboarding-dialog.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/utils/i18n.js
src/extension/content.js
test/app/components/onboarding/onboarding-modal.test.js

fix(onboarding): reuse appStore theme and fix sort order

---

src/extension/_locales/en/messages.json
src/extension/app/store/app.js
test/app/store/app.test.js

fix: inexistent source doc opens blank page

---

src/extension/_locales/en/messages.json
src/extension/app/components/plugin/plugin-action-bar.js

chore(i18n): hardcoded strings

---

src/extension/_locales/de/messages.json
src/extension/_locales/es/messages.json
src/extension/_locales/fr/messages.json
src/extension/_locales/it/messages.json
src/extension/_locales/ja/messages.json
src/extension/_locales/ko/messages.json
src/extension/_locales/pt_BR/messages.json
src/extension/_locales/zh_CN/messages.json
src/extension/_locales/zh_TW/messages.json

Translations Update, please integrate

---

src/extension/_locales/de/messages.json
src/extension/_locales/en/messages.json
src/extension/_locales/es/messages.json
src/extension/_locales/fr/messages.json
src/extension/_locales/it/messages.json
src/extension/_locales/ja/messages.json
src/extension/_locales/ko/messages.json
src/extension/_locales/pt_BR/messages.json
src/extension/_locales/zh_CN/messages.json
src/extension/_locales/zh_TW/messages.json
src/extension/app/components/dialog-wrapper/dialog-wrapper.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/store/app.js
src/extension/ui.js
test/app/store/app.test.js
test/ui.test.js

fix: internal release

---

package-lock.json
src/extension/actions.js
src/extension/app/components/plugin/login/login.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/store/app.js
src/extension/auth.js
src/extension/background.js
test/actions.test.js
test/app/components/plugin/login.test.js
test/app/components/plugin/plugin-action-bar.test.js
test/app/store/app.test.js

feat: display profile picture

---

.eslintrc.cjs
.releaserc.cjs
build/build-browser.js
package.json
rollup.config.js
src/extension/app/store/app.js
src/extension/manifest.json

chore: remove safari-specific code

---

src/extension/content.js
src/extension/tab.js

chore: support ci admin versions

---

src/extension/app/spectrum-2.css.js

fix: disabled action buttons color

---

.eslintrc.cjs
.releaserc.cjs
build/build-browser.js
package.json
rollup.config.js
src/extension/app/spectrum-2.css.js
src/extension/app/store/app.js
src/extension/content.js
src/extension/manifest.json
src/extension/tab.js
src/extension/utils/admin.js
test/utils/admin.test.js

Fix #344 
Fix #354 
Fix #359 
Fix #356

chore: release 20241114

---

src/extension/app/store/app.js
src/extension/app/store/site.js
src/extension/content.js

chore: remove obsolete authTokenExpiry handling

---

src/extension/app/plugins/preview/preview.js
test/app/plugins/preview/preview.test.js

fix(preview): empty error message

---

src/extension/app/components/onboarding/onboarding-dialog.js

fix(onboarding): hardcoded aria-label on close button

---

src/extension/app/store/app.js
test/app/store/app.test.js

fix(sharepoint): mp4 viewer causes 404 in status

---

src/extension/app/store/bulk.js
test/aem-sidekick.test.js
test/app/store/bulk.test.js
web-test-runner.config.mjs

fix(bulk): illegal file path handling

---

src/extension/ui.js
test/ui.test.js

fix(view-doc-source): check any url

---

src/extension/app/store/bulk.js
test/fixtures/content-sources.js

fix(bulk): detect selection in gdrive grid

---

src/extension/views/json/json.js

use locale string instead of UTC

---

src/extension/app/store/bulk.js
src/extension/views/json/json.js
test/fixtures/content-sources.js

chore: release 20241216

---

src/extension/_locales/en/messages.json
src/extension/app/components/bulk/bulk-result/bulk-result.js
src/extension/app/constants.js
src/extension/app/store/site.js
src/extension/app/utils/admin-client.js
src/extension/app/utils/i18n.js
src/extension/types/typedefs.js
test/app/store/app.test.js
test/app/utils/admin-client.test.js

feat: user-friendly server error messages

---

src/extension/_locales/de/messages.json
src/extension/_locales/en/messages.json
src/extension/_locales/es/messages.json
src/extension/_locales/fr/messages.json
src/extension/_locales/it/messages.json
src/extension/_locales/ja/messages.json
src/extension/_locales/ko/messages.json
src/extension/_locales/pt_BR/messages.json
src/extension/_locales/zh_CN/messages.json
src/extension/_locales/zh_TW/messages.json
src/extension/app/store/app.js
src/extension/app/store/bulk.js
test/app/store/bulk.test.js

fix(bulk): consistent UI previewing config files

---

src/extension/views/json/json.js

fix(json): table header and body can be mismatched

---

src/extension/_locales/de/messages.json
src/extension/_locales/en/messages.json
src/extension/_locales/es/messages.json
src/extension/_locales/fr/messages.json
src/extension/_locales/it/messages.json
src/extension/_locales/ja/messages.json
src/extension/_locales/ko/messages.json
src/extension/_locales/pt_BR/messages.json
src/extension/_locales/zh_CN/messages.json
src/extension/_locales/zh_TW/messages.json

fix(i18n): readd deleted strings

---

src/extension/app/utils/admin-client.js
test/app/utils/admin-client.test.js

fix: better localized config error messages

---

src/extension/_locales/de/messages.json
src/extension/_locales/en/messages.json
src/extension/_locales/es/messages.json
src/extension/_locales/fr/messages.json
src/extension/_locales/it/messages.json
src/extension/_locales/ja/messages.json
src/extension/_locales/ko/messages.json
src/extension/_locales/pt_BR/messages.json
src/extension/_locales/zh_CN/messages.json
src/extension/_locales/zh_TW/messages.json
src/extension/app/utils/admin-client.js
src/extension/views/json/json.js
test/app/utils/admin-client.test.js

- Empty error message when attempting to preview Office documents from Google Drive
- Unlocalized error message on failure to activate configuration file
- JSON view displayed in light mode by default
- Fixes #442
- Fixes #436
- Fixes #446

RC-20250128

---

src/extension/app/aem-sidekick.css.js

fix(css): body text-align bleed

---

src/extension/_locales/en/messages.json
src/extension/views/json/json.js

fix(json): improved empty message

---

.circleci/config.yml
package-lock.json
package.json
src/extension/_locales/de/messages.json
src/extension/_locales/en/messages.json
src/extension/_locales/es/messages.json
src/extension/_locales/fr/messages.json
src/extension/_locales/it/messages.json
src/extension/_locales/ja/messages.json
src/extension/_locales/ko/messages.json
src/extension/_locales/pt_BR/messages.json
src/extension/_locales/zh_CN/messages.json
src/extension/_locales/zh_TW/messages.json
src/extension/actions.js
src/extension/app/aem-sidekick.css.js
src/extension/app/components/plugin/plugin-action-bar.css.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/components/plugin/plugin.js
src/extension/app/spectrum-2.css.js
src/extension/app/store/app.js
src/extension/index.js
src/extension/types/typedefs.js
src/extension/views/json/json.js
test/actions.test.js
test/app/components/plugin/plugin.test.js

- Prevent body styles from bleeding into sidekick
- JSON view: improved empty message
- Fixed close button rendering issue when many plugins in bar
- #123 
- #441 
- #472

RC-20250218

---

src/extension/_locales/en/messages.json
src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.js
src/extension/app/components/plugin/plugin.js
src/extension/app/spectrum-2.css.js
src/extension/app/store/app.js
src/extension/app/store/site.js
src/extension/app/utils/browser.js
src/extension/auth.js
src/extension/project.js
src/extension/types/typedefs.js
test/app/components/plugin/env-switcher.test.js
test/app/components/plugin/plugin.test.js
test/app/store/app.test.js
test/app/store/site.test.js
test/auth.test.js
test/mocks/environment.js
test/project.test.js

feat: support aem.reviews

---

.eslintrc.cjs
src/extension/actions.js
test/actions.test.js

feat: launch externally

---

.renovaterc.json
package-lock.json
package.json
src/extension/actions.js
src/extension/auth.js
test/actions.test.js
test/auth.test.js

RC-20250326

---

src/extension/_locales/en/messages.json
src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.js
test/app/components/plugin/env-switcher.test.js
test/fixtures/helix-admin.js

feat: show user with last mod date

---

src/extension/actions.js
src/extension/app/plugins/publish/publish.js
src/extension/app/store/app.js
test/actions.test.js
test/app/store/app.test.js
test/fixtures/html-output.js
test/fixtures/payloads.js

feat: switch to live instead of production if not aem

---

src/extension/content.js

fix: toggle config picker

---

src/extension/_locales/de/messages.json
src/extension/_locales/en/messages.json
src/extension/_locales/es/messages.json
src/extension/_locales/fr/messages.json
src/extension/_locales/it/messages.json
src/extension/_locales/ja/messages.json
src/extension/_locales/ko/messages.json
src/extension/_locales/pt_BR/messages.json
src/extension/_locales/zh_CN/messages.json
src/extension/_locales/zh_TW/messages.json
src/extension/actions.js
src/extension/app/components/action-bar/menu-item/menu-item.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.css.js
src/extension/app/components/plugin/env-switcher/env-switcher.js
src/extension/app/plugins/publish/publish.js
src/extension/app/store/app.js
src/extension/content.js
test/actions.test.js
test/app/components/plugin/env-switcher.test.js
test/app/store/app.test.js
test/fixtures/helix-admin.js
test/fixtures/payloads.js

RC-20250402

---

package-lock.json
package.json
src/extension/ui.js

fix(guessAEMSite): DOM check not tight enough

---

src/extension/actions.js
src/extension/app/store/site.js
test/actions.test.js
test/app/components/plugin/plugin-action-bar.test.js
test/app/store/site.test.js

feat: auto-update of added project

---

src/extension/app/store/app.js
src/extension/content.js
test/app/store/app.test.js

fix: hide the overflow caused by the pre element in JSON view

---

src/extension/app/utils/admin-client.js
test/app/utils/admin-client.test.js

fix: show x-error on 400 preview error if no error code

---

src/extension/actions.js
test/actions.test.js

feat: trigger login flow for org

---

src/extension/actions.js
test/actions.test.js

Fix #552
also:
- login using IDP of choice

feat: allow trusted origins to update project config

---

src/extension/actions.js
test/actions.test.js

Fixes a bug introduced in #553

fix: update site deletes project properties

---

src/extension/app/store/bulk.js
test/app/store/bulk.test.js
test/fixtures/content-sources.js

fix(bulk): selection no longer detected in sharepoint

---

src/extension/views/json/json.js

fix(json): arabic and hebrew displayed ltr

---

src/extension/app/store/bulk.js
test/fixtures/content-sources.js

fix: broken bulk selection when gemini is enabled in gdrive

---

src/extension/app/components/plugin/plugin-action-bar.css.js
src/extension/app/components/plugin/plugin-action-bar.js
src/extension/app/components/plugin/plugin.js
src/extension/app/store/app.js
src/extension/types/typedefs.js
test/app/components/plugin/plugin.test.js

fix: popover plugin not working in menu

---

src/extension/views/json/json.js

fix(json): revert #398

---

src/extension/app/store/bulk.js
test/app/store/bulk.test.js
test/fixtures/content-sources.js
test/sidekick-test.js

fix(bulk): google drive selection no longer recognized

---

src/extension/auth.js
test/auth.test.js

fix: also inject site token in sub frames

---

src/extension/actions.js
src/extension/app/aem-sidekick.js
src/extension/project.js
test/actions.test.js
test/aem-sidekick.test.js
test/project.test.js

fix: add project failing with site that is not originalSite

---

src/extension/app/store/app.js
test/app/components/plugin/plugin.test.js

fix: passConfig does not pass all custom hosts

---

src/extension/app/store/site.js
test/app/store/site.test.js

fix: only update existing project if status 200

---

src/extension/app/plugins/preview/preview.js
src/extension/app/store/site.js
src/extension/types/typedefs.js
test/app/store/site.test.js

feat(preview): configurable word save delay

---

src/extension/actions.js
src/extension/auth.js
test/actions.test.js
test/auth.test.js

fix: token expiry calculation

---

src/extension/_locales/en/messages.json
src/extension/app/constants.js
test/app/utils/admin-client.test.js

refactor: update error code templates

---

src/extension/url-cache.js
test/url-cache.test.js

fix: add project hints for gdrive lookup

---

src/extension/url-cache.js
test/url-cache.test.js

feat: optimize sharepoint lookups
