src/extension/app/components/plugin/plugin-action-bar.js, src/extension/app/plugins/preview/preview.js, src/extension/app/store/app.js, test/wtr/aem-config-picker.test.js, test/wtr/app/components/modal/modal.test.js, test/wtr/app/components/plugin/env-switcher.test.js, test/wtr/app/components/plugin/palette-container.test.js, test/wtr/app/components/plugin/plugin-action-bar.test.js, test/wtr/app/components/toast/toast.test.js, test/wtr/app/plugins/preview/preview.test.js, test/wtr/app/store/app.test.js, test/wtr/fixtures/helix-admin.js, test/wtr/mocks/environment.js, test/wtr/mocks/helix-admin.js
- Preview plugin tests
- Support disabled state in core plugins
- Abstract window.location.reload for testing
- Update test fixtures to include payloads for gdrive and sharepoint
- update and updatePreview coverage in appStore
=> fix: Preview plugin tests

src/extension/app/components/action-bar/picker/picker.css.js, src/extension/app/components/plugin/env-switcher/env-switcher.js, src/extension/app/store/app.js, src/extension/app/utils/browser.js, src/extension/app/utils/keyboard.js, test/app/components/plugin/env-switcher.test.js
=> fix: Plugin container button color, new tab on switching to edit env

src/extension/url-cache.js
Port from https://github.com/adobe/helix-sidekick-extension/pull/690
=> fix: url cache entry expiry always in the past

src/extension/app/store/app.js, test/app/store/app.test.js
Toast was broken when activating `/.helix/config`
Improved tests around `updatePreview`
=> fix: toast when activating config, improve tests

src/extension/_locales/en/messages.json, src/extension/app/components/plugin/env-switcher/env-switcher.js, src/extension/app/store/app.js, src/extension/manifest.json, test/app/components/plugin/env-switcher.test.js, test/app/store/app.test.js
The environment switcher tells the user which content source we will switch to when hitting the edit button. This PR makes that detection more robust and also will hide the button when it's a BYOM project.
Also allow-listed more of the files required to render the json view.
=> fix: improve content source detection in environment switcher

src/extension/background.js, src/extension/content.js
If the sidekick is hidden and then opened multiple requests are being made to admin for sidekick config and status. This seemed to be caused by the call to `checkTab` I added. Instead of calling `checkTab` when the display state changes in local storage I am instead just calling updateIcon which is all I needed to do in the first place.
=> fix: don't call checkTab if sidekick hidden from ui

src/extension/project.js, test/project.test.js
=> fix: don't drop project name from share settings

src/extension/app/utils/admin-client.js, test/app/utils/admin-client.test.js
The job API requires users to be signed in for operations on more than 100 URLs.
=> chore: handle 401 from bulk job creation

src/extension/content.js
Fixes: #251 
Removing the `nocache` at the start of the content script was causing `checkTab` to be called multiple times in a row which resulted in the aem-sidekick element getting injected into the page multiple times. Multiple events were fired before the element was added to page, our check to make sure not to add it twice was then failing.
`const sidekick = document.querySelector('aem-sidekick');` is still undefined as these events are fired.
=> fix: don't remove nocache at start of content script

src/extension/app/store/app.js, src/extension/app/store/site.js, src/extension/types/typedefs.js, test/app/store/app.test.js, test/app/store/site.test.js
* Provides ability to let project spec an `editUrlFormat` object
* Supports `{{contentSourceUrl}} {{org}} {{site}} {{pathname}}` placeholders in pattern
```json
{
"project": "XWalk Block Collection",
"editUrlLabel": "Universal Editor",
"editUrlPattern": "{{contentSourceUrl}}{{pathname}}?cmd=open"
}
```
```json
{
"project": "DA Block Collection",
"editUrlLabel": "Document Authoring",
"editUrlPattern": "https://da.live/edit#/{{org}}/{{site}}{{pathname}}"
}
```
Resolves: GH-244
See the GH issue.
E2E for now. Once approach is agreed upon, will write tests.
=> GH-244 - Extensible source support

test/app/plugins/unpublish/unpublish.test.js
This brings the code coverage back for toast timeout actions in plugin action bar.
=> test: toast timeout action

src/extension/app/components/action-bar/menu-item/menu-item.css.js, src/extension/app/components/plugin/env-switcher/env-switcher.js, src/extension/manifest.json, test/app/components/plugin/plugin-action-bar.test.js, test/app/store/app.test.js, test/fixtures/helix-admin.js
[env-switcher] visually align "source" item with the others in the popover (along with last modified/edited timestamp)
Fix #283 
**Preview:**
**Editor:**
=> feat: Visually align Source in Editor view [env-switcher]

package-lock.json, src/extension/_locales/en/messages.json, src/extension/actions.js, src/extension/app/aem-sidekick.js, src/extension/app/components/dialog-wrapper/dialog-wrapper.css.js, src/extension/app/components/modal/modal-container.js, src/extension/app/constants.js, src/extension/background.js, src/extension/manifest.json, src/extension/project.js, test/actions.test.js, test/aem-sidekick.test.js, test/app/components/modal/modal.test.js, test/project.test.js
Move away from using native chrome notifications to in page notifications served by the sidekick. We have seen that there are many factors that could cause chrome notifications to not be displayed, by moving to in page notifications we can
guarantee that our notification is seen.
=> Rework notifications

src/extension/utils/admin.js, test/utils/admin.test.js
Since the AEM Sidekick no longer uses cookies for authentication to Admin, we can remove the `credentials: 'include'` option from fetch requests to Admin.
The sidekick no longer uses cookie based authentication, so `credentials: 'include'`  should be dropped.
Manually the following flows in the browser:
Site with Admin Without login (Sharepoint)
* Preview
* Publish
* Login
* Status
* Profile
* Logout
* Unpublish
* Delete
Site with Admin With login (Sharepoint)
* Login
* Logout
* Preview
* Publish
* Status
* Profile
* Unpublish
* Delete
* Extensions loaded
Site with Admin with login (Google Drive)
* Login
* Logout
* Preview
* Publish
* Status
* Profile
* Unpublish
* Delete
Unit tests currently not working locally, but passing in the CI.
=> fix: cookie-less auth cleanup. remove credentials: include

web-test-runner.config.mjs
Fix #351 
Browser logs can still be inspected by going into focus mode (F) and turning on browser debugging (D).
=> chore(test): less verbosity

package-lock.json, src/extension/views/json/json.js
Adding functionality to Json View to watch for the changes to theme config from sidekick and applying those to view when changed / toggled between "light" or "dark" theme.
#383 
There is an issue created #383 . Applying the same theme as sidekick to the json view makes sense so that the UI experience is better by making the view back ground matching the sidekick color
By installing the extension locally after building and tested both "preview" and "publish" urls of a sample ".json"
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix: apply the theme selected on sidekick to json view

src/extension/app/aem-sidekick.css.js, src/extension/app/components/action-bar/activity-action/activity-action.css.js, src/extension/app/components/onboarding/onboarding-dialog.css.js
If the sidekick installed along side of JSONVue extension , the sidekick action bar in json prev is not rendering correctly. 
Also when the white space css property is adjusted for action bar , the onboarding modal did not render correctly . The cross icon and other elements are not in place.
Sidekick
- Width is more
- Icons on action bar are not visible
Onboarding Modal 
- the cross icon is not accurately placed
- the onboarding modal window size is not correct 
Adjusting css property (white-space) for aem-sidekick and onboarding-dialog web components
fix #422 
JSONVue extension is used by almost 1 million users , so the chances of the this occurring is more even though it will not happen when the particular extension is not used along side of sidekick
Tested the sidekick fixes with or …
=> fix : sidekick size and icon placements are not correct when JSON Vue extension available

src/extension/views/json/json.js
Searching after entering any keyword in multi sheet was making the JSON view dis-appear and default to json data view.
#421 
Fixing the search functionality for multi sheet json . There were  some recent changes to view to accommodate header and body content alignment - https://github.com/adobe/aem-sidekick/pull/412  that needed change to include columns in to the sheet object on search
- Created a multi sheet 
- Previewed the json and tested the search functionality
- Created a single sheet
- Previewed and tested the search functionality
=> fix: search in multi sheet json - on search adding columns along with filtered data

src/extension/app/store/app.js, src/extension/content.js
Listening to the sidekick "hidden" event to reset the display of json content from json view
#428 
Showing blank page when sidekick is closed while viewing json content is not a good user experience, rather resetting back to original json content is ideal.
After making the necessary code changes , built and used that extension to
- Test the intended functionality is not causing any regression for the page by testing "preview" , "live" web pages
- Tested on "preview" , "live" json views . Hiding sidekick will close json view and defaults to json content
=> fix: displaying the json content when sidekick is closed 

src/extension/views/json/json.js, test/fixtures/singlesheet.json
Checking whether a string starting with single forward slash or not to be considered as relative url. Utilizing the regex instead of startsWith('/')
#426 
Issue created by QA team as sometimes the spread sheet may have strings starts with "//".
- created a spreadsheet with "//" 
- previewed the json
- make sure that json view does not break
- able to search for "//"
=> fix: strings starting with // characters break preview of spreadsheet

src/extension/views/json/json.js
Default theme for JSON View was "light" and changing that to "dark" which aligns with the default theme of the side kick.
Fix #442 
Keeps the JSON view initial background theme inline with the sidekick theme
- Built and Installed the sidekick extension in a chrome browser , after making the code changes
- Manually  tested , validated that the initial theme is dark
- Toggled the theme on sidekick , which is applied for the json view as expectd
=> fix: setting initial theme as dark for json view

src/extension/project.js, test/project.test.js
- Multiple project matches no longer lead to empty picker buttons
- Fixes #449
=> fix: ensure every project match has an id

src/extension/app/spectrum-2.css.js
Fix #472 
Quick fix: add 5px to `--sidekick-max-width`
=> fix: close button overhang

src/extension/actions.js, test/actions.test.js
=> feat: allow tools.aem.live and labs.aem.live to list configured sites

src/extension/app/store/bulk.js, test/app/store/bulk.test.js, test/fixtures/content-sources.js
fixes: #488 
Older sharepoint DOM had the following `aria-label` on the selected elements
`bla.docx, docx File, Private, Modified 8/28/2023, edited by Jane, 1 KB`
The newer design just has `bla.docx`.
=> fix: support newer sharepoint structure

src/extension/auth.js, test/auth.test.js
Discussed with @auniverseaway 
Since users login into DA and DA is sending its own authentication header, the sidekick should not be trying to inject its own here.
In some cases, it can give confusing errors. E.g. there is a mismatch in the IMS org selected during login between sidekick and DA.
The way that chrome works is that this also applies to subdomains of `da.live`.
Will have to see if in the future this may cause problems.
Manually in the browser.
=> fix: Do not inject admin token for requests originating on da.live

src/extension/_locales/zh_CN/messages.json, src/extension/views/json/json.js
- Check if the value we want to format is an Array and format accordingly
- Hide results count in JSON view if not present in JSON data
- Fix toggle view issue when there are multiple sheets and the json hasn't been published yet
https://github.com/adobe/aem-sidekick/issues/648
https://github.com/adobe/aem-sidekick/issues/520
https://github.com/adobe/aem-sidekick/issues/617
Helix JSON (found in query-index.json commonly) can have arrays in the values for each column. We don't have a case for that currently which breaks the json view.
Hide results count if original json doesn't have the total
When live json 404s, check if multi sheet and set up a dummy json without data so that the show changes still works
Tested the links from the slack thread to make sure it works well
=> fix: json view bug fixes

src/extension/app/components/plugin/login/login.js, test/app/components/plugin/login.test.js
Changes login component so when the config call returns 403, user is able to logout. 
Note: in the original issues I talked about different auth sources, but I don't think that matters. I think the root cause is that the sidekick stores and injects the auth token based on the org, but different sites within that org could allow/disallow different sets users. 
I ran into it is because on one site I logged in using my @adobe.com account, but on the other site, access was only allowed for my personal @gmail.com account. I don't think it matters that these use different auth providers, just that they are different accounts/email addresses within a single org. I think the same thing would happen if a single person logged into one site as name@company.com but wanted to log into another site as …
=> Login handle 403

src/extension/app/store/app.js, test/app/store/app.test.js
=> fix(env-switcher): source label always falls back on contentSourceType
